<a href="https://colab.research.google.com/github/Anirookie/Anirookie/blob/main/Tweet_sentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("train.csv")
df2 = pd.read_csv("test.csv")

In [3]:
df1

Tweets     label
0    Asked #ChatGPT about what it thinks are the pr...  Positive
1    #ChatGPT tornado has already traveled around t...   Neutral
2    This is a great explanation of why #EVs are mo...  Positive
3    ‘if you need to write a box-ticking social med...  Positive
4    Just saw an AI tool making my coffee for me. \...  Positive
..                                                 ...       ...
765                                                NaN       NaN
766                                                NaN       NaN
767                                                NaN       NaN
768                                                NaN       NaN
769                                                NaN       NaN

[770 rows x 2 columns]

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770 entries, 0 to 769
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Tweets  599 non-null    object
 1   label   599 non-null    object
dtypes: object(2)
memory usage: 12.2+ KB


In [5]:
df1.isnull().sum()

Tweets    171
label     171
dtype: int64

In [5]:
df1=df1.dropna(how='all')

In [6]:
df1

Tweets     label
0    Asked #ChatGPT about what it thinks are the pr...  Positive
1    #ChatGPT tornado has already traveled around t...   Neutral
2    This is a great explanation of why #EVs are mo...  Positive
3    ‘if you need to write a box-ticking social med...  Positive
4    Just saw an AI tool making my coffee for me. \...  Positive
..                                                 ...       ...
594  4. GPT’s AI capabilities are also more accessi...  Positive
595  3. KeyboardX also provides a more secure envir...  Positive
596  2. KeyboardX allows users to quickly and easil...  Positive
597  I asked ChatGPT why the app I’m working on, Ke...  Positive
598  There's been a lot of talk about AI engines an...  Positive

[599 rows x 2 columns]

In [67]:
df1.isnull().sum()

Tweets    0
label     0
dtype: int64

In [7]:
df1['label'].value_counts()

Positive    378
Negative    143
Neutral      78
Name: label, dtype: int64

In [83]:
df1['Tweets'][0]

'Asked #ChatGPT about what it thinks are the problems associated with urbanisation in India &amp; the solutions to be adopted to boost public transport use in our cities. Interesting set of responses. \n\n#EconTwitter #UrbanEconomics @sselvan https://t.co/yTyD2ypxDh'

In [40]:
syl=['#@$&!*']
for i in df1["Tweets"]:
  if i in syl:
    print(i)

In [8]:
df1['Tweets'][594]

'4. GPT’s AI capabilities are also more accessible on KeyboardX, as users can access them with just a few taps. #OpenAI #ChatGPT #GPT #KeyboardX #AI #BuildInPublic'

In [69]:
import re

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 2 columns):
 #   Column                                                                               Non-Null Count  Dtype 
---  ------                                                                               --------------  ----- 
 0   @CoffeeVectors @jenny____r confirmed #ChatGPT has dad jokes https://t.co/tC2Sks2f76  170 non-null    object
 1   Positive                                                                             170 non-null    object
dtypes: object(2)
memory usage: 2.8+ KB


In [9]:

import re

In [10]:
df1.columns

Index(['Tweets', 'label'], dtype='object')

In [11]:
df1['Tweets'][4]

'Just saw an AI tool making my coffee for me. \n#ChatGPT #AI #AIMagic'

In [86]:
for column in df1.columns:
  df1[column]=df1[column].replace("\n", "", regex=True, inplace=True)

<ipython-input-86-c0365d76a2d5>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column]=df1[column].replace("\n", "", regex=True, inplace=True)
<ipython-input-86-c0365d76a2d5>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column]=df1[column].replace("\n", "", regex=True, inplace=True)


In [12]:
df1

Tweets     label
0    Asked #ChatGPT about what it thinks are the pr...  Positive
1    #ChatGPT tornado has already traveled around t...   Neutral
2    This is a great explanation of why #EVs are mo...  Positive
3    ‘if you need to write a box-ticking social med...  Positive
4    Just saw an AI tool making my coffee for me. \...  Positive
..                                                 ...       ...
594  4. GPT’s AI capabilities are also more accessi...  Positive
595  3. KeyboardX also provides a more secure envir...  Positive
596  2. KeyboardX allows users to quickly and easil...  Positive
597  I asked ChatGPT why the app I’m working on, Ke...  Positive
598  There's been a lot of talk about AI engines an...  Positive

[599 rows x 2 columns]

In [13]:
def remove_special_characters(df1):
  for column in df1.columns:
    df1[column]=df1[column].apply(lambda x:re.sub(r'[^\w\s\d]','', x))
  return df1

df =remove_special_characters(df1)

<ipython-input-13-bd1ce796e708>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column]=df1[column].apply(lambda x:re.sub(r'[^\w\s\d]','', x))


In [14]:
df

Tweets     label
0    Asked ChatGPT about what it thinks are the pro...  Positive
1    ChatGPT tornado has already traveled around th...   Neutral
2    This is a great explanation of why EVs are mor...  Positive
3    if you need to write a boxticking social media...  Positive
4    Just saw an AI tool making my coffee for me \n...  Positive
..                                                 ...       ...
594  4 GPTs AI capabilities are also more accessibl...  Positive
595  3 KeyboardX also provides a more secure enviro...  Positive
596  2 KeyboardX allows users to quickly and easily...  Positive
597  I asked ChatGPT why the app Im working on Keyb...  Positive
598  Theres been a lot of talk about AI engines and...  Positive

[599 rows x 2 columns]

In [15]:
import nltk

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
# Stop words removal
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

In [ ]:
stop_words

In [24]:
df.head()

Tweets     label
0  Asked ChatGPT thinks problems associated urban...  Positive
1  ChatGPT tornado already traveled around world ...   Neutral
2  This great explanation EVs efficient energy AN...  Positive
3  need write boxticking social media post using ...  Positive
4  Just saw AI tool making coffee ChatGPT AI AIMagic  Positive

In [17]:
X = df.drop('label',axis=1)
y=df['label']

In [18]:
X.shape,y.shape

((599, 1), (599,))

In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
vocab_size=300

In [21]:
tweets = X.copy()

In [22]:
tweets

Tweets
0    Asked ChatGPT about what it thinks are the pro...
1    ChatGPT tornado has already traveled around th...
2    This is a great explanation of why EVs are mor...
3    if you need to write a boxticking social media...
4    Just saw an AI tool making my coffee for me \n...
..                                                 ...
594  4 GPTs AI capabilities are also more accessibl...
595  3 KeyboardX also provides a more secure enviro...
596  2 KeyboardX allows users to quickly and easily...
597  I asked ChatGPT why the app Im working on Keyb...
598  Theres been a lot of talk about AI engines and...

[599 rows x 1 columns]

In [23]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(tweets)):
    review =re.sub('[^a-zA-Z]', ' ', tweets['Tweets'][i])
    review =review.lower()
    review= review.split()

    review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review =' '.join(review)
    corpus.append(review)

In [24]:
corpus

['ask chatgpt think problem associ urbanis india amp solut adopt boost public transport use citi interest set respons econtwitt urbaneconom sselvan httpstcoytyd ypxdh',
 'chatgpt tornado alreadi travel around world sever time start understand much gener ai could chang way work scare ye excit ye critic sens ever ai linkedincompulsenewway',
 'great explan ev effici energi sourc chatgpt combust engin even impress yingshirleymeng',
 'need write boxtick social media post use establish inform fill boot nice post pro con consider ai comm pr iojosi ai chatgpt comm',
 'saw ai tool make coffe chatgpt ai aimag',
 'trust chatgpt write bug free code least yet even bot doesnt recommend put code product l abl write bug free code b languag model abl gener code base exampl pattlnkdind df vs',
 'tonight friend wonder scienc topic instead web search read wikipedia articl ask chatgpt read quick summari answer save sort time mean digcit search skill',
 'rise popular chatgpt signal chang offer glimps onlin 

In [25]:
onehot_repr=[one_hot(words,vocab_size)for words in corpus]
onehot_repr

[[268,
  271,
  156,
  209,
  200,
  133,
  206,
  119,
  43,
  248,
  127,
  268,
  278,
  99,
  42,
  249,
  55,
  238,
  282,
  4,
  14,
  148,
  217],
 [271,
  232,
  227,
  253,
  290,
  147,
  82,
  79,
  173,
  138,
  53,
  210,
  180,
  179,
  121,
  31,
  56,
  17,
  280,
  226,
  280,
  54,
  174,
  222,
  180,
  58],
 [155, 268, 253, 16, 181, 116, 271, 191, 22, 120, 216, 51],
 [76,
  255,
  201,
  158,
  110,
  138,
  99,
  296,
  68,
  280,
  242,
  91,
  138,
  118,
  79,
  243,
  180,
  55,
  218,
  151,
  180,
  271,
  55],
 [186, 180, 197, 168, 237, 271, 180, 181],
 [224,
  271,
  255,
  238,
  85,
  287,
  80,
  258,
  120,
  278,
  165,
  219,
  136,
  287,
  132,
  152,
  10,
  255,
  238,
  85,
  287,
  264,
  255,
  185,
  10,
  210,
  287,
  141,
  81,
  285,
  89,
  274],
 [287,
  102,
  28,
  127,
  44,
  1,
  268,
  116,
  216,
  189,
  220,
  268,
  271,
  216,
  208,
  274,
  120,
  297,
  211,
  79,
  213,
  42,
  116,
  209],
 [269,
  89,
  271,
  132,
  12

In [ ]:
onehot_repr[1]

In [28]:
# Embedding
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [33]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[209 200 133 ...  14 148 217]
 [ 82  79 173 ... 222 180  58]
 [155 268 253 ...   0   0   0]
 ...
 [ 70  87 282 ... 104   0   0]
 [ 70 222  99 ...  93 106 184]
 [133 291 180 ...  21 244 175]]


In [34]:
embedded_docs[25:32]

array([[109, 271, 116,  22, 267,  99, 231, 281, 286,  23, 164,  34, 287,
        158, 271, 246, 270,  68, 167,   0],
       [281, 271, 180,  98,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [ 43, 271, 168, 188, 198,  79, 212, 238, 213, 285,  10, 280,   0,
          0,   0,   0,   0,   0,   0,   0],
       [277,  23,  43,  85, 268, 194, 197,  93, 210, 213, 180, 137, 126,
        231, 146, 271,   0,   0,   0,   0],
       [268, 271,  34, 282, 133, 156, 208, 196,  66, 271, 179,  33, 210,
        279,  38,  67, 179, 206,   0,   0],
       [255, 215, 116, 286, 259, 216, 288, 138, 127, 255,  91, 271, 180,
         45,  45,   0,   0,   0,   0,   0],
       [271, 187,  29,  75, 265, 125, 265, 291,  90, 220, 199, 262, 271,
          0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [35]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [61]:
model = Sequential()
embedding_vector=40 ##features representation
model.add(Embedding(vocab_size,embedding_vector,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            12000     
                                                                 
 lstm_4 (LSTM)               (None, 100)               56400     
                                                                 
 dense_4 (Dense)             (None, 1)                 101       
                                                                 
Total params: 68501 (267.58 KB)
Trainable params: 68501 (267.58 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [62]:
len(embedded_docs),y.shape

(599, (599,))

In [63]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [64]:
X_final.shape,y_final.shape

((599, 20), (599,))

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.3, random_state=42)

In [69]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10


UnimplementedError: Graph execution error:

Detected at node categorical_crossentropy/Cast defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>

  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start

  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "<ipython-input-66-269a536dfafa>", line 1, in <cell line: 1>

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1807, in fit

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1151, in train_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1209, in compute_loss

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/compile_utils.py", line 277, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 143, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 270, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 2198, in categorical_crossentropy

Cast string to float is not supported
	 [[{{node categorical_crossentropy/Cast}}]] [Op:__inference_train_function_13994]

In [67]:
y_test

array(['Positive', 'Positive', 'Positive', 'Positive', 'Negative',
       'Positive', 'Neutral', 'Positive', 'Neutral', 'Positive',
       'Positive', 'Negative', 'Negative', 'Positive', 'Negative',
       'Positive', 'Neutral', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Negative',
       'Neutral', 'Negative', 'Negative', 'Negative', 'Neutral',
       'Positive', 'Negative', 'Positive', 'Positive', 'Negative',
       'Negative', 'Neutral', 'Neutral', 'Positive', 'Positive',
       'Negative', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Positive', 'Neutral', 'Neutral', 'Negative',
       'Negative', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Negative', 'Negative', 'Negative', 'Positive',
       'Positive', 'Positive', 'Positive', 'Negative', 'Negative',
    